import html
import os
import smtplib
from email.message import EmailMessage
from typing import Any, List, Mapping

def _build_html(items: List[Mapping[str, Any]]) -> str:
    """Build a modern, clean HTML digest for podcasts."""
    items_html = ""
    for item in items:
        summary_html = ""
        for line in item.get("summary", []):
            summary_html += f'<li style="margin-bottom: 6px; line-height: 1.5;">{html.escape(str(line))}</li>'
            
        title = html.escape(str(item.get("title", "Untitled Episode")))
        podcast_name = html.escape(str(item.get("podcast_name", item.get("podcast", "Podcast"))))
        published = html.escape(str(item.get("published", "Recent")))
        link = item.get("link", "")
        
        title_tag = f'<a href="{html.escape(link, quote=True)}" style="color: #2563eb; text-decoration: none; font-weight: 700;">{title}</a>' if link else title
        button_tag = f'<div style="margin-top: 14px;"><a href="{html.escape(link, quote=True)}" style="display: inline-block; background-color: #0ea5e9; color: #ffffff; padding: 8px 14px; border-radius: 6px; text-decoration: none; font-size: 13px; font-weight: 600;">🎧 Listen / View Episode</a></div>' if link else ''
        
        items_html += f"""
        <article style="margin-bottom: 24px; padding: 20px; background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
            <div style="font-size: 13px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px;">
                {podcast_name}
            </div>
            <h3 style="margin: 0 0 8px 0; font-size: 18px; line-height: 1.4;">
                {title_tag}
            </h3>
            <p style="margin: 0 0 14px 0; font-size: 13px; color: #94a3b8;">
                📅 Published: {published}
            </p>
            <ul style="margin: 0; padding-left: 20px; color: #334155; font-size: 14px;">
                {summary_html if summary_html else "<li>Episode notes summarized from publisher metadata.</li>"}
            </ul>
            {button_tag}
        </article>
        """
        
    return f"""<!doctype html>
    <html>
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
    <body style="background-color: #f8fafc; color: #0f172a; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 24px 16px;">
        <main style="max-width: 680px; margin: 0 auto;">
            <header style="margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #e2e8f0;">
                <h1 style="color: #0f172a; font-size: 24px; margin: 0 0 6px 0;">🎙️ Podcast Intelligence Digest</h1>
                <p style="color: #64748b; font-size: 14px; margin: 0;">Curated publisher insights & episode highlights</p>
            </header>
            {items_html if items_html else '<p style="color: #64748b;">No new episodes found in configured feeds.</p>'}
            <footer style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 12px; text-align: center;">
                Generated by Public Podcast Summarizer · Zero media downloads · Publisher metadata verified
            </footer>
        </main>
    </body>
    </html>
    """

def send_digest(items: List[Mapping[str, Any]], dry_run: bool = False) -> None:
    """Send the HTML digest via SMTP."""
    host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    port = int(os.environ.get("SMTP_PORT", 587))
    user = os.environ.get("SMTP_USER")
    password = os.environ.get("SMTP_PASSWORD")
    recipient = os.environ.get("REPORT_RECIPIENT")
    
    html_content = _build_html(items)
    
    if dry_run:
        print("--- DRY RUN: Would send email ---")
        print(f"Recipient: {recipient}")
        print(html_content[:500] + "...")
        return
        
    if not all([host, port, user, password, recipient]):
        print("Warning: Missing SMTP credentials. Skipping email delivery.")
        return
        
    msg = EmailMessage()
    msg["Subject"] = f"🎙️ Podcast Digest: {len(items)} Episode(s) Summary"
    msg["From"] = f"Podcast Summarizer <{user}>"
    msg["To"] = recipient
    msg.set_content("Please view this email in an HTML-compatible client.")
    msg.add_alternative(html_content, subtype="html")
    
    with smtplib.SMTP(host, port) as server:
        server.starttls()
        server.login(user, password)
        server.send_message(msg)
    print(f"Podcast digest email successfully sent to {recipient}")
